title: davidpri1
logo: "/images/IMG_0931.jpg" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science Hub 
  <br><br>
  All learning, All the time
  <br><br>
  <a href="https://www.linkedin.com/in/davidpri/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-153607751-1 
